/*
 * This file is generated by jOOQ.
 */
package com.gramant.campmodel.data.tables.records;


import com.gramant.campmodel.data.tables.Campaign;
import com.gramant.campmodel.domain.Campaign.Calculation;

import java.util.UUID;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CampaignRecord extends UpdatableRecordImpl<CampaignRecord> implements Record6<UUID, String, UUID, Calculation, Integer, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>CAMPAIGN.ID</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>CAMPAIGN.ID</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>CAMPAIGN.NAME</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>CAMPAIGN.NAME</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>CAMPAIGN.PRODUCT_CODE</code>.
     */
    public void setProductCode(UUID value) {
        set(2, value);
    }

    /**
     * Getter for <code>CAMPAIGN.PRODUCT_CODE</code>.
     */
    public UUID getProductCode() {
        return (UUID) get(2);
    }

    /**
     * Setter for <code>CAMPAIGN.CALCULATION</code>.
     */
    public void setCalculation(Calculation value) {
        set(3, value);
    }

    /**
     * Getter for <code>CAMPAIGN.CALCULATION</code>.
     */
    public Calculation getCalculation() {
        return (Calculation) get(3);
    }

    /**
     * Setter for <code>CAMPAIGN.BUDGET</code>.
     */
    public void setBudget(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>CAMPAIGN.BUDGET</code>.
     */
    public Integer getBudget() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>CAMPAIGN.WEEKS</code>.
     */
    public void setWeeks(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>CAMPAIGN.WEEKS</code>.
     */
    public Integer getWeeks() {
        return (Integer) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<UUID, String, UUID, Calculation, Integer, Integer> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<UUID, String, UUID, Calculation, Integer, Integer> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return Campaign.CAMPAIGN.ID;
    }

    @Override
    public Field<String> field2() {
        return Campaign.CAMPAIGN.NAME;
    }

    @Override
    public Field<UUID> field3() {
        return Campaign.CAMPAIGN.PRODUCT_CODE;
    }

    @Override
    public Field<Calculation> field4() {
        return Campaign.CAMPAIGN.CALCULATION;
    }

    @Override
    public Field<Integer> field5() {
        return Campaign.CAMPAIGN.BUDGET;
    }

    @Override
    public Field<Integer> field6() {
        return Campaign.CAMPAIGN.WEEKS;
    }

    @Override
    public UUID component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public UUID component3() {
        return getProductCode();
    }

    @Override
    public Calculation component4() {
        return getCalculation();
    }

    @Override
    public Integer component5() {
        return getBudget();
    }

    @Override
    public Integer component6() {
        return getWeeks();
    }

    @Override
    public UUID value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public UUID value3() {
        return getProductCode();
    }

    @Override
    public Calculation value4() {
        return getCalculation();
    }

    @Override
    public Integer value5() {
        return getBudget();
    }

    @Override
    public Integer value6() {
        return getWeeks();
    }

    @Override
    public CampaignRecord value1(UUID value) {
        setId(value);
        return this;
    }

    @Override
    public CampaignRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public CampaignRecord value3(UUID value) {
        setProductCode(value);
        return this;
    }

    @Override
    public CampaignRecord value4(Calculation value) {
        setCalculation(value);
        return this;
    }

    @Override
    public CampaignRecord value5(Integer value) {
        setBudget(value);
        return this;
    }

    @Override
    public CampaignRecord value6(Integer value) {
        setWeeks(value);
        return this;
    }

    @Override
    public CampaignRecord values(UUID value1, String value2, UUID value3, Calculation value4, Integer value5, Integer value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CampaignRecord
     */
    public CampaignRecord() {
        super(Campaign.CAMPAIGN);
    }

    /**
     * Create a detached, initialised CampaignRecord
     */
    public CampaignRecord(UUID id, String name, UUID productCode, Calculation calculation, Integer budget, Integer weeks) {
        super(Campaign.CAMPAIGN);

        setId(id);
        setName(name);
        setProductCode(productCode);
        setCalculation(calculation);
        setBudget(budget);
        setWeeks(weeks);
    }
}
