/*
 * This file is generated by jOOQ.
 */
package com.gramant.campmodel.data.tables.records;


import com.gramant.campmodel.data.tables.Company;

import java.util.UUID;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CompanyRecord extends UpdatableRecordImpl<CompanyRecord> implements Record6<UUID, String, UUID, String, Integer, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>COMPANY.ID</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>COMPANY.ID</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>COMPANY.NAME</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>COMPANY.NAME</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>COMPANY.PRODUCT_ID</code>.
     */
    public void setProductId(UUID value) {
        set(2, value);
    }

    /**
     * Getter for <code>COMPANY.PRODUCT_ID</code>.
     */
    public UUID getProductId() {
        return (UUID) get(2);
    }

    /**
     * Setter for <code>COMPANY.CALCULATION</code>.
     */
    public void setCalculation(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>COMPANY.CALCULATION</code>.
     */
    public String getCalculation() {
        return (String) get(3);
    }

    /**
     * Setter for <code>COMPANY.BUDGET</code>.
     */
    public void setBudget(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>COMPANY.BUDGET</code>.
     */
    public Integer getBudget() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>COMPANY.WEEKS</code>.
     */
    public void setWeeks(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>COMPANY.WEEKS</code>.
     */
    public Integer getWeeks() {
        return (Integer) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<UUID, String, UUID, String, Integer, Integer> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<UUID, String, UUID, String, Integer, Integer> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return Company.COMPANY.ID;
    }

    @Override
    public Field<String> field2() {
        return Company.COMPANY.NAME;
    }

    @Override
    public Field<UUID> field3() {
        return Company.COMPANY.PRODUCT_ID;
    }

    @Override
    public Field<String> field4() {
        return Company.COMPANY.CALCULATION;
    }

    @Override
    public Field<Integer> field5() {
        return Company.COMPANY.BUDGET;
    }

    @Override
    public Field<Integer> field6() {
        return Company.COMPANY.WEEKS;
    }

    @Override
    public UUID component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public UUID component3() {
        return getProductId();
    }

    @Override
    public String component4() {
        return getCalculation();
    }

    @Override
    public Integer component5() {
        return getBudget();
    }

    @Override
    public Integer component6() {
        return getWeeks();
    }

    @Override
    public UUID value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public UUID value3() {
        return getProductId();
    }

    @Override
    public String value4() {
        return getCalculation();
    }

    @Override
    public Integer value5() {
        return getBudget();
    }

    @Override
    public Integer value6() {
        return getWeeks();
    }

    @Override
    public CompanyRecord value1(UUID value) {
        setId(value);
        return this;
    }

    @Override
    public CompanyRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public CompanyRecord value3(UUID value) {
        setProductId(value);
        return this;
    }

    @Override
    public CompanyRecord value4(String value) {
        setCalculation(value);
        return this;
    }

    @Override
    public CompanyRecord value5(Integer value) {
        setBudget(value);
        return this;
    }

    @Override
    public CompanyRecord value6(Integer value) {
        setWeeks(value);
        return this;
    }

    @Override
    public CompanyRecord values(UUID value1, String value2, UUID value3, String value4, Integer value5, Integer value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CompanyRecord
     */
    public CompanyRecord() {
        super(Company.COMPANY);
    }

    /**
     * Create a detached, initialised CompanyRecord
     */
    public CompanyRecord(UUID id, String name, UUID productId, String calculation, Integer budget, Integer weeks) {
        super(Company.COMPANY);

        setId(id);
        setName(name);
        setProductId(productId);
        setCalculation(calculation);
        setBudget(budget);
        setWeeks(weeks);
    }
}
