/*
 * This file is generated by jOOQ.
 */
package com.gramant.campmodel.data.tables.records;


import com.gramant.campmodel.data.tables.Products;

import java.util.UUID;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProductsRecord extends UpdatableRecordImpl<ProductsRecord> implements Record2<UUID, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>PRODUCTS.CODE</code>.
     */
    public void setCode(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>PRODUCTS.CODE</code>.
     */
    public UUID getCode() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>PRODUCTS.NAME</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>PRODUCTS.NAME</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<UUID, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<UUID, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return Products.PRODUCTS.CODE;
    }

    @Override
    public Field<String> field2() {
        return Products.PRODUCTS.NAME;
    }

    @Override
    public UUID component1() {
        return getCode();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public UUID value1() {
        return getCode();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public ProductsRecord value1(UUID value) {
        setCode(value);
        return this;
    }

    @Override
    public ProductsRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public ProductsRecord values(UUID value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProductsRecord
     */
    public ProductsRecord() {
        super(Products.PRODUCTS);
    }

    /**
     * Create a detached, initialised ProductsRecord
     */
    public ProductsRecord(UUID code, String name) {
        super(Products.PRODUCTS);

        setCode(code);
        setName(name);
    }
}
