/*
 * This file is generated by jOOQ.
 */
package com.gramant.campmodel.data.tables.records;


import com.gramant.campmodel.data.tables.Product;

import java.util.UUID;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProductRecord extends UpdatableRecordImpl<ProductRecord> implements Record2<UUID, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>PRODUCT.CODE</code>.
     */
    public void setCode(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>PRODUCT.CODE</code>.
     */
    public UUID getCode() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>PRODUCT.NAME</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>PRODUCT.NAME</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<UUID, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<UUID, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return Product.PRODUCT.CODE;
    }

    @Override
    public Field<String> field2() {
        return Product.PRODUCT.NAME;
    }

    @Override
    public UUID component1() {
        return getCode();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public UUID value1() {
        return getCode();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public ProductRecord value1(UUID value) {
        setCode(value);
        return this;
    }

    @Override
    public ProductRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public ProductRecord values(UUID value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProductRecord
     */
    public ProductRecord() {
        super(Product.PRODUCT);
    }

    /**
     * Create a detached, initialised ProductRecord
     */
    public ProductRecord(UUID code, String name) {
        super(Product.PRODUCT);

        setCode(code);
        setName(name);
    }
}
