/*
 * This file is generated by jOOQ.
 */
package com.gramant.campmodel.data;


import com.gramant.campmodel.data.tables.Company;
import com.gramant.campmodel.data.tables.Products;


/**
 * Convenience access to all tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>COMPANY</code>.
     */
    public static final Company COMPANY = Company.COMPANY;

    /**
     * The table <code>PRODUCTS</code>.
     */
    public static final Products PRODUCTS = Products.PRODUCTS;
}
