/*
 * This file is generated by jOOQ.
 */
package com.gramant.campmodel.data;


import com.gramant.campmodel.data.tables.Campaign;
import com.gramant.campmodel.data.tables.Product;


/**
 * Convenience access to all tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>CAMPAIGN</code>.
     */
    public static final Campaign CAMPAIGN = Campaign.CAMPAIGN;

    /**
     * The table <code>PRODUCT</code>.
     */
    public static final Product PRODUCT = Product.PRODUCT;
}
