/*
 * This file is generated by jOOQ.
 */
package com.gramant.campmodel.data.tables;


import com.gramant.campmodel.data.DefaultSchema;
import com.gramant.campmodel.data.Keys;
import com.gramant.campmodel.data.tables.records.CampaignRecord;

import java.util.Arrays;
import java.util.List;
import java.util.UUID;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row6;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Campaign extends TableImpl<CampaignRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>CAMPAIGN</code>
     */
    public static final Campaign CAMPAIGN = new Campaign();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CampaignRecord> getRecordType() {
        return CampaignRecord.class;
    }

    /**
     * The column <code>CAMPAIGN.ID</code>.
     */
    public final TableField<CampaignRecord, UUID> ID = createField(DSL.name("ID"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>CAMPAIGN.NAME</code>.
     */
    public final TableField<CampaignRecord, String> NAME = createField(DSL.name("NAME"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>CAMPAIGN.PRODUCT_ID</code>.
     */
    public final TableField<CampaignRecord, UUID> PRODUCT_ID = createField(DSL.name("PRODUCT_ID"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>CAMPAIGN.CALCULATION</code>.
     */
    public final TableField<CampaignRecord, String> CALCULATION = createField(DSL.name("CALCULATION"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>CAMPAIGN.BUDGET</code>.
     */
    public final TableField<CampaignRecord, Integer> BUDGET = createField(DSL.name("BUDGET"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>CAMPAIGN.WEEKS</code>.
     */
    public final TableField<CampaignRecord, Integer> WEEKS = createField(DSL.name("WEEKS"), SQLDataType.INTEGER.nullable(false), this, "");

    private Campaign(Name alias, Table<CampaignRecord> aliased) {
        this(alias, aliased, null);
    }

    private Campaign(Name alias, Table<CampaignRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>CAMPAIGN</code> table reference
     */
    public Campaign(String alias) {
        this(DSL.name(alias), CAMPAIGN);
    }

    /**
     * Create an aliased <code>CAMPAIGN</code> table reference
     */
    public Campaign(Name alias) {
        this(alias, CAMPAIGN);
    }

    /**
     * Create a <code>CAMPAIGN</code> table reference
     */
    public Campaign() {
        this(DSL.name("CAMPAIGN"), null);
    }

    public <O extends Record> Campaign(Table<O> child, ForeignKey<O, CampaignRecord> key) {
        super(child, key, CAMPAIGN);
    }

    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public UniqueKey<CampaignRecord> getPrimaryKey() {
        return Keys.PK_COMPANY_ID;
    }

    @Override
    public List<UniqueKey<CampaignRecord>> getKeys() {
        return Arrays.<UniqueKey<CampaignRecord>>asList(Keys.PK_COMPANY_ID, Keys.UQ_COMPANY_NAME, Keys.PRODUCT_ID);
    }

    @Override
    public List<ForeignKey<CampaignRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<CampaignRecord, ?>>asList(Keys.FK_COMPANY);
    }

    public Products products() {
        return new Products(this, Keys.FK_COMPANY);
    }

    @Override
    public Campaign as(String alias) {
        return new Campaign(DSL.name(alias), this);
    }

    @Override
    public Campaign as(Name alias) {
        return new Campaign(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Campaign rename(String name) {
        return new Campaign(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Campaign rename(Name name) {
        return new Campaign(name, null);
    }

    // -------------------------------------------------------------------------
    // Row6 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row6<UUID, String, UUID, String, Integer, Integer> fieldsRow() {
        return (Row6) super.fieldsRow();
    }
}
