/*
 * This file is generated by jOOQ.
 */
package com.gramant.campmodel.data.tables;


import com.gramant.campmodel.data.DefaultSchema;
import com.gramant.campmodel.data.Keys;
import com.gramant.campmodel.data.tables.records.CompanyRecord;

import java.util.Arrays;
import java.util.List;
import java.util.UUID;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row6;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Company extends TableImpl<CompanyRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>COMPANY</code>
     */
    public static final Company COMPANY = new Company();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CompanyRecord> getRecordType() {
        return CompanyRecord.class;
    }

    /**
     * The column <code>COMPANY.ID</code>.
     */
    public final TableField<CompanyRecord, UUID> ID = createField(DSL.name("ID"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>COMPANY.NAME</code>.
     */
    public final TableField<CompanyRecord, String> NAME = createField(DSL.name("NAME"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>COMPANY.PRODUCT_ID</code>.
     */
    public final TableField<CompanyRecord, UUID> PRODUCT_ID = createField(DSL.name("PRODUCT_ID"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>COMPANY.CALCULATION</code>.
     */
    public final TableField<CompanyRecord, String> CALCULATION = createField(DSL.name("CALCULATION"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>COMPANY.BUDGET</code>.
     */
    public final TableField<CompanyRecord, Integer> BUDGET = createField(DSL.name("BUDGET"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>COMPANY.WEEKS</code>.
     */
    public final TableField<CompanyRecord, Integer> WEEKS = createField(DSL.name("WEEKS"), SQLDataType.INTEGER.nullable(false), this, "");

    private Company(Name alias, Table<CompanyRecord> aliased) {
        this(alias, aliased, null);
    }

    private Company(Name alias, Table<CompanyRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>COMPANY</code> table reference
     */
    public Company(String alias) {
        this(DSL.name(alias), COMPANY);
    }

    /**
     * Create an aliased <code>COMPANY</code> table reference
     */
    public Company(Name alias) {
        this(alias, COMPANY);
    }

    /**
     * Create a <code>COMPANY</code> table reference
     */
    public Company() {
        this(DSL.name("COMPANY"), null);
    }

    public <O extends Record> Company(Table<O> child, ForeignKey<O, CompanyRecord> key) {
        super(child, key, COMPANY);
    }

    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public UniqueKey<CompanyRecord> getPrimaryKey() {
        return Keys.PK_COMPANY_ID;
    }

    @Override
    public List<UniqueKey<CompanyRecord>> getKeys() {
        return Arrays.<UniqueKey<CompanyRecord>>asList(Keys.PK_COMPANY_ID, Keys.UQ_COMPANY_NAME, Keys.PRODUCT_ID);
    }

    @Override
    public List<ForeignKey<CompanyRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<CompanyRecord, ?>>asList(Keys.FK_COMPANY);
    }

    public Products products() {
        return new Products(this, Keys.FK_COMPANY);
    }

    @Override
    public Company as(String alias) {
        return new Company(DSL.name(alias), this);
    }

    @Override
    public Company as(Name alias) {
        return new Company(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Company rename(String name) {
        return new Company(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Company rename(Name name) {
        return new Company(name, null);
    }

    // -------------------------------------------------------------------------
    // Row6 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row6<UUID, String, UUID, String, Integer, Integer> fieldsRow() {
        return (Row6) super.fieldsRow();
    }
}
